from django.db import models

class DiaryRecord(models.Model):
    DiaryRecordNo = models.CharField(max_length=10, primary_key=True)
    ProjectNo = models.IntegerField(max_length=5)
    RecordDate = models.DateField()
    RecordShift = models.CharField(max_length=10)
    Supervisor = models.CharField(max_length=100)
    DelayAccess = models.BooleanField(default=False)
    DelayLackOfDrawing = models.BooleanField(default=False)
    DelayAwaitClientDecision = models.BooleanField(default=False)
    DelayPoorWeather = models.BooleanField(default=False)
    DelayIndustrialMatters = models.BooleanField(default=False)
    DelayAwaitClientInstruction = models.BooleanField(default=False)
    DelaySubcontractors = models.BooleanField(default=False)
    DelayAwaitMaterials = models.BooleanField(default=False)
    DelayRework = models.BooleanField(default=False)
    DelayOther = models.CharField(max_length=255, null=True, blank=True)
    DelayDetails = models.TextField(null=True, blank=True)
    ActivityDiscussion = models.TextField(null=True, blank=True)
    SafetyIssueDiscussion = models.TextField(null=True, blank=True)
    InstructionFromClient = models.TextField(null=True, blank=True)
    VisitorOnSite = models.TextField(null=True, blank=True)
    DailyProgressDescription = models.TextField(null=True, blank=True)
    RecordComment = models.TextField(null=True, blank=True)
    HandoverNote = models.TextField(null=True, blank=True)
    JhaQty = models.IntegerField(default=0)
    CccQty = models.IntegerField(default=0)
    Take5Qty = models.IntegerField(default=0)
    StopSeekQty = models.IntegerField(default=0)
    MobilisedQty = models.IntegerField(default=0)
    NonManualQty = models.IntegerField(default=0)
    ManualQty = models.IntegerField(default=0)
    SubcontractorQty = models.IntegerField(default=0)
    IncidentQty = models.IntegerField(default=0)
    NearMissQty = models.IntegerField(default=0)
    FirstAidQty = models.IntegerField(default=0)
    MedicallyTreatedInjuryQty = models.IntegerField(default=0)
    LossTimeInjuryQty = models.IntegerField(default=0)

    def __str__(self):
        return f"Diary Record: {self.DiaryRecordNo}, Project No: {self.ProjectNo}, Date: {self.RecordDate}"
    
class DayTracking(models.Model):
    DayTrakingNo = models.CharField(max_length=50, primary_key= True)
    Project = models.CharField(max_length=100)
    RecordDate = models.DateField()
    RecordDay = models.CharField(max_length=10)
    Shift = models.CharField(max_length=50)
    WorkArea = models.CharField(max_length=255)
    ClientRepresentative = models.CharField(max_length=100)
    Weather = models.CharField(max_length=100)
    Employee = models.CharField(max_length=100)
    Role = models.CharField(max_length=100)
    HourRate = models.FloatField()
    StartTime = models.TimeField()
    EndTime = models.TimeField()
    TotalHours = models.DecimalField(max_digits=10, decimal_places=2)
    WorkDescription = models.CharField(max_length=255)
    CostItemId = models.CharField(max_length=50)
    HourRate = models.FloatField()
    StartTime = models.TimeField()
    EndTime = models.TimeField()
    TotalHours = models.DecimalField(max_digits=5, decimal_places=2)
    TotalCost = models.DecimalField(max_digits=10, decimal_places=2)
    WorkDescription = models.CharField(max_length=255)
    Comments = models.TextField(null=True, blank=True)
    KaddumName = models.CharField(max_length=100, blank=True, null=True)
    KaddumSign = models.ImageField(upload_to='kaddum_signs/', blank=True, null=True)
    KaddumSignDate = models.DateField(blank=True, null=True)
    ClientName = models.CharField(max_length=100, blank=True, null=True)
    ClientSign = models.ImageField(upload_to='client_signs/', blank=True, null=True)
    ClientSignDate = models.DateField(blank=True, null=True)
    SubmittedDate = models.DateField()

    def __str__(self):
        return f"Day Tracking:{self.DayTrakingNo} "

class CostTracking(models.Model):
    LineItemNo = models.IntegerField(primary_key=True)
    Project = models.CharField(max_length=100)
    Date = models.DateField()
    Day = models.CharField(max_length=10)
    Shift = models.CharField(max_length=50)
    YearWeek = models.CharField(max_length=10)
    Employee = models.CharField(max_length=100)
    ConfirmRole = models.CharField(max_length=100)
    ConfirmRate = models.FloatField()
    ConfirmStartTime = models.TimeField()
    ConfirmEndTime = models.TimeField()
    ConfirmTotalHour = models.DecimalField(max_digits=5, decimal_places=2)
    ConfirmTotalCost = models.DecimalField(max_digits=10, decimal_places=2)
    Indigenous = models.BooleanField()
    Local = models.BooleanField()

    def __str__(self):
        return str(self.LineItemNo)