# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from dashboard.models import ResourceCost
from datetime import date

class Command(BaseCommand):
    help = 'Seeds the database with ResourceCost'

    def handle(self, *args, **options):
        self.stdout.write('Seeding ResourceCost data...')

        records = [
            {
                'item_type': 'personel',
                'item_name': 'ERA Supervisor',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 12.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Allrounder',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 9.50,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Moxy Operator',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 8.70,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {

                'item_type': 'personel',
                'item_name': 'ERA Amex Operator',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 11.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Trade Assistant Dayshift',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 8.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Trade Assistant Nightshift',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 9.20,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Deck Hand',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 9.50,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Master 5',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 12.50,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'ERA Mechanical Fitter / Operator',
                'item_id': None,
                'item_location': 'ERA',
                'item_rate': 11.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Supervisor',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 11.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'All Rounder',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 9.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Operator',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 8.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Plumber',
                'item_id': None,
                'item_location': None,
                'item_rate': 12.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Electrician',
                'item_id': None,
                'item_location': None,
                'item_rate': 12.20,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Electricain HV',
                'item_id': None,
                'item_location': None,
                'item_rate': 14.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'General Labourer',
                'item_id': None,
                'item_location': None,
                'item_rate': 6.50,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Structual Draftsman',
                'item_id': None,
                'item_location': None,
                'item_rate': 9.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'personel',
                'item_name': 'Structual Engineer',
                'item_id': None,
                'item_location': None,
                'item_rate': 22.00,
                'unit_of_measure': 'hour',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Toyota Landcruiser Ute Trayback',
                'item_id': 'KV01',
                'item_location': 'Jabiru',
                'item_rate': 15.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Toyota Landcruiser Ute Trayback',
                'item_id': 'KV02',
                'item_location': 'Jabiru',
                'item_rate': 15.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Toyata Hilux Dual Cab',
                'item_id': 'KV03',
                'item_location': 'Jabiru',
                'item_rate': 15.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Toyata Hilux Dual Cab',
                'item_id': 'KV04',
                'item_location': 'Jabiru',
                'item_rate': 15.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Mitsubishi Triton Dual Cab',
                'item_id': 'KV05',
                'item_location': 'Jabiru',
                'item_rate': 13.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'car',
                'item_name': 'Toyota Troop Carrier',
                'item_id': 'KV06',
                'item_location': 'Jabiru',
                'item_rate': 13.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Isuzu 10m Body Tipper',
                'item_id': 'KM01',
                'item_location': 'Jabiru',
                'item_rate': 45.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
                {
                'item_type': 'truck',
                'item_name': 'Rigid 16m Tipper',
                'item_id': None,
                'item_location': None,
                'item_rate': 67.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Isuzu beavertail 14t with 4t Hiab 9 tonne winch',
                'item_id': 'KM02',
                'item_location': 'Jabiru',
                'item_rate': 45.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Rigid 14000L Water Cart',
                'item_id': None,
                'item_location': None,
                'item_rate': 70.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Hino FS 700 Series 10m Tipper includes trailer',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 65.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Isuzu FY FTR Bucket Truck',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 120.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Isuzu Hydroexcavation Unit',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 180.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Hino 500 Series Flat Bed',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 48.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Hino FDIJLPA Tipper 4m',
                'item_id': None,
                'item_location': 'Jabiru',
                'item_rate': 48.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': 'to be provided',
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Slip on 5,000L water tank with dribble bar',
                'item_id': 'KM03',
                'item_location': 'Jabiru',
                'item_rate': 10.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
            {
                'item_type': 'truck',
                'item_name': 'Slip on 10,000L water tank with dribble bar',
                'item_id': 'KM04',
                'item_location': 'Jabiru',
                'item_rate': 15.00,
                'unit_of_measure': 'day',
                'mobilisation_desc': None,
                'last_update_date': date(2024, 4, 22),
            },
        ]

        for record_data in records:
            ResourceCost.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded ResourceCost data!'))
