# kaddumapp/management/commands/seed_dairy_records.py
from django.core.management.base import BaseCommand
from dashboard.models import DairyRecord
from datetime import date

class Command(BaseCommand):
    help = 'Seeds the database with DairyRecord data'

    def handle(self, *args, **options):
        self.stdout.write('Seeding DairyRecord data...')

        records =  [
            {
                'dairy_record_no': 'DR00001',
                'project_no': '2425',
                'record_date': date(2024, 4, 22),
                'record_shift': 'dayshift',
                'supervisor': 'Kabi',
                'activity_discussion': 'Activity discussion details here.',
                'safety_issue_discussion': 'Safety issue discussion details here.',
                'instruction_from_client': 'Instructions from client here.',
                'visitor_on_site': None,
                'daily_progress_description': 'Daily progress description here.',
                'record_comment': 'Record comment here.',
                'handover_note': 'Handover note here.',
                'record_created_date': date(2024, 4, 22),
                'record_submitted_date': date(2024, 4, 22),
                'delay_access': True,
                'delay_lack_of_drawing': False,
                'delay_await_client_decision': False,
                'delay_poor_weather': False,
                'delay_industrial_matters': False,
                'delay_await_client_instruction': False,
                'delay_subcontractors': True,
                'delay_await_materials': False,
                'delay_rework': False,
                'delay_other': False,
                'delay_details': 'out of stock',
                'jha_qty': 3,
                'ccc_qty': 1,
                'take5_qty': 1,
                'stop_seek_qty': 0,
                'mobilised_qty': 2,
                'non_manual_qty': 1,
                'manual_qty': 1,
                'subcontractor_qty': 1,
                'incident_qty': 1,
                'near_miss_qty': 1,
                'first_aid_qty': 2,
                'medically_treated_injury_qty': 1,
                'loss_time_injury_qty': 0,
                'is_draft':False,
            },
            {
                'dairy_record_no': 'DR00002',
                'project_no': '2425',
                'record_date': date(2024, 4, 22),
                'record_shift': 'nightshift',
                'supervisor': 'Kabi',
                'activity_discussion': 'Activity discussion details here.',
                'safety_issue_discussion': 'Safety issue discussion details here.',
                'instruction_from_client': 'Instructions from client here.',
                'visitor_on_site': None,
                'daily_progress_description': 'Daily progress description here.',
                'record_comment': 'Record comment here.',
                'handover_note': 'Handover note here.',
                'record_created_date': date(2024, 4, 22),
                'record_submitted_date': date(2024, 4, 22),
                'delay_access': True,
                'delay_lack_of_drawing': False,
                'delay_await_client_decision': False,
                'delay_poor_weather': False,
                'delay_industrial_matters': False,
                'delay_await_client_instruction': False,
                'delay_subcontractors': True,
                'delay_await_materials': True,
                'delay_rework': True,
                'delay_other': False,
                'delay_details': 'out of stock',
                'jha_qty': 3,
                'ccc_qty': 1,
                'take5_qty': 1,
                'stop_seek_qty': 0,
                'mobilised_qty': 2,
                'non_manual_qty': 1,
                'manual_qty': 1,
                'subcontractor_qty': 1,
                'incident_qty': 1,
                'near_miss_qty': 1,
                'first_aid_qty': 2,
                'medically_treated_injury_qty': 1,
                'loss_time_injury_qty': 0,
                'is_draft':False,
            },
            {
                'dairy_record_no': 'DR00003',
                'project_no': '2429',
                'record_date': date(2024, 4, 22),
                'record_shift': 'nightshift',
                'supervisor': 'Kabi',
                'activity_discussion': 'Activity discussion details here.',
                'safety_issue_discussion': 'Safety issue discussion details here.',
                'instruction_from_client': 'Instructions from client here.',
                'visitor_on_site': None,
                'daily_progress_description': 'Daily progress description here.',
                'record_comment': 'Record comment here.',
                'handover_note': 'Handover note here.',
                'record_created_date': date(2024, 4, 22),
                'record_submitted_date': date(2024, 4, 22),
                'delay_access': True,
                'delay_lack_of_drawing': False,
                'delay_await_client_decision': False,
                'delay_poor_weather': False,
                'delay_industrial_matters': False,
                'delay_await_client_instruction': False,
                'delay_subcontractors': True,
                'delay_await_materials': True,
                'delay_rework': True,
                'delay_other': False,
                'delay_details': 'out of stock',
                'jha_qty': 3,
                'ccc_qty': 1,
                'take5_qty': 1,
                'stop_seek_qty': 0,
                'mobilised_qty': 2,
                'non_manual_qty': 1,
                'manual_qty': 1,
                'subcontractor_qty': 1,
                'incident_qty': 1,
                'near_miss_qty': 1,
                'first_aid_qty': 2,
                'medically_treated_injury_qty': 1,
                'loss_time_injury_qty': 0,
                'is_draft':True,
            },
        ]

        for record_data in records:
            DairyRecord.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded DairyRecord data!'))
