# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from users.models import UserAccount
from datetime import date

class Command(BaseCommand):
    help = 'Seeds the database with UserAccount'

    def handle(self, *args, **options):
        self.stdout.write('Seeding UserAccount data...')

        records = [
            {
                'username': 'KD0001',
                'first_name': 'Melissa',
                'last_name': 'Pettersson',
                'full_name': 'Melissa Pettersson',
                'indigenous': True,
                'local': True,
                'position': 'ERA Supervisor',
                'roles': 'supervisor',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
            },
            {
                'username': 'KD0002',
                'full_name': 'Joseph Jeffries',
                'first_name': 'Joseph',
                'last_name': 'Jeffries',
                'position': 'ERA Allrounder',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0003',
                'full_name': 'Rik Erkelens',
                'first_name': 'Rik',
                'last_name': 'Erkelens',
                'position': 'ERA Moxy Operator',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0004',
                'full_name': 'David Cook',
                'first_name': 'David',
                'last_name': 'Cook',
                'position': 'ERA Amex Operator',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0005',
                'full_name': 'Dave Bulte',
                'first_name': 'Dave',
                'last_name': 'Bulte',
                'position': 'ERA Trade Assistant Dayshift',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0006',
                'full_name': 'Andrew Clark',
                'first_name': 'Andrew',
                'last_name': 'Clark',
                'position': 'ERA Trade Assistant Nightshift',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0007',
                'full_name': 'Katie Kiwikiwi',
                'first_name': 'Katie',
                'last_name': 'Kiwikiwi',
                'position': 'ERA Deck Hand',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': False,
            },
            {
                'username': 'KD0008',
                'full_name': 'Justin hooker',
                'first_name': 'Justin',
                'last_name': 'hooker',
                'position': 'ERA Master 5',
                'roles': 'restricted user',  # You haven't provided a role for this user, please update accordingly
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0009',
                'full_name': 'Clinton Rasmussen',
                'first_name': 'Clinton',
                'last_name': 'Rasmussen',
                'position': 'ERA Mechanical Fitter / Operator',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': True,
            },
            {
                'username': 'KD0010',
                'full_name': 'Mark Reidys',
                'first_name': 'Mark',
                'last_name': 'Reidys',
                'position': 'Supervisor',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0011',
                'full_name': 'Tippene Shepherd',
                'first_name': 'Tippene',
                'last_name': 'Shepherd',
                'position': 'All Rounder',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': False,
            },
            {
                'username': 'KD0012',
                'full_name': 'Greg McKinnon',
                'first_name': 'Greg',
                'last_name': 'McKinnon',
                'position': 'Operator',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0013',
                'full_name': 'Nicole Bancroft',
                'first_name': 'Nicole',
                'last_name': 'Bancroft',
                'position': 'Plumber',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0014',
                'full_name': 'Jason Mousley',
                'first_name': 'Jason',
                'last_name': 'Mousley',
                'position': 'Electrician',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0015',
                'full_name': 'Joe Horvath',
                'first_name': 'Joe',
                'last_name': 'Horvath',
                'position': 'Electricain HV',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0016',
                'full_name': 'Stefan Anderson',
                'first_name': 'Stefan',
                'last_name': 'Anderson',
                'position': 'General Labourer',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0017',
                'full_name': 'John Smith',
                'first_name': 'John',
                'last_name': 'Smith',
                'position': 'Supervisor',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0018',
                'full_name': 'Alice Johnson',
                'first_name': 'Alice',
                'last_name': 'Johnson',
                'position': 'Electrician Apprentice',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0019',
                'full_name': 'Emily Brown',
                'first_name': 'Emily',
                'last_name': 'Brown',
                'position': 'Plumber Apprentice',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': True,
            },
            {
                'username': 'KD0020',
                'full_name': 'Michael Wilson',
                'first_name': 'Michael',
                'last_name': 'Wilson',
                'position': 'General Labourer Apprentice',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0021',
                'full_name': 'Emma Lee',
                'first_name': 'Emma',
                'last_name': 'Lee',
                'position': 'Safety Officer',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': False,
            },
            {
                'username': 'KD0022',
                'full_name': 'Sophia Williams',
                'first_name': 'Sophia',
                'last_name': 'Williams',
                'position': 'Administrative Assistant',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
            {
                'username': 'KD0023',
                'full_name': 'Matthew Thompson',
                'first_name': 'Matthew',
                'last_name': 'Thompson',
                'position': 'Safety Inspector',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': True,
                'local': False,
            },
            {
                'username': 'KD0024',
                'full_name': 'Olivia Davis',
                'first_name': 'Olivia',
                'last_name': 'Davis',
                'position': 'HR Manager',
                'roles': 'restricted user',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'indigenous': False,
                'local': False,
            },
        ]

        for record_data in records:
            UserAccount.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded UserAccount data!'))
