# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from dashboard.models import DayTracking, Project, CostTracking
from datetime import date, datetime

class Command(BaseCommand):
    help = 'Seeds the database with DayTracking data'

    def handle(self, *args, **options):
        self.stdout.write('Seeding DayTracking data...')
        projects = {str(project.project_no): project for project in Project.objects.all()}
        cost_trackings = {str(cost_tracking.cost_tracking_id): cost_tracking for cost_tracking in CostTracking.objects.all()}

        records = [
            {
                'day_tracking_id': 'DS00001',
                'cost_tracking_id': cost_trackings['CT00001'],
                'project_no': projects['2425'],
                'record_date': date(2024, 5, 2),
                'record_shift': 'Day Shift',
                'year_week': '202417',                
                'work_area': 'Dust Mitigation Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'Kabi',
                'kaddum_sign': 'Kabi',
                'kaddum_sign_date': date(2024, 5, 2),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 2),
                'created_date':datetime(2024,5,2,10,20,30),
                'last_modification_date': datetime(2024,5,2,10,20,30),
                'total_hours_employee': 20,
                'total_hours_employee_local': 10,
                'total_hours_employee_indigenous': 10,
                'total_amount_employee': 200,
                'total_hours_equipment': 20,
                'total_amount_equipment': 2000,
            },
            {
                'day_tracking_id': 'DS00002',
                'cost_tracking_id': cost_trackings['CT00001'],
                'project_no': projects['2425'],
                'record_date': date(2024, 5, 2),
                'record_shift': 'Night Shift',
                'year_week': '202417',  
                'work_area': 'Dust Mitigation Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'chen',
                'kaddum_sign': 'chen',
                'kaddum_sign_date': date(2024, 5, 2),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 2),
                'created_date':datetime(2024,5,2,18,20,30),
                'last_modification_date': datetime(2024,5,2,18,20,30),
                'is_draft': False,
                'total_hours_employee':60,
                'total_hours_employee_local': 30,
                'total_hours_employee_indigenous': 30,
                'total_amount_employee': 600,
                'total_hours_equipment': 0,
                'total_amount_equipment': 0,                
            },
            {
                'day_tracking_id': 'DS00003',
                'cost_tracking_id': cost_trackings['CT00002'],
                'project_no': projects['2425'],
                'record_date': date(2024, 5, 3),
                'record_shift': 'Day Shift',
                'year_week': '202417',
                'work_area': 'Dust Mitigation Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'Kabi',
                'kaddum_sign': 'Kabi',
                'kaddum_sign_date': date(2024, 5, 3),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 3),
                'created_date':datetime(2024,5,3,10,20,30),
                'last_modification_date': datetime(2024,5,3,10,20,30),
                'is_draft': False,
                'total_hours_employee':20,
                'total_hours_employee_local': 10,
                'total_hours_employee_indigenous': 10,
                'total_amount_employee': 200,
                'total_hours_equipment': 10,
                'total_amount_equipment': 1000,          
            },
            {
                'day_tracking_id': 'DS00004',
                'cost_tracking_id': cost_trackings['CT00002'],
                'project_no': projects['2425'],
                'record_date': date(2024, 5, 3),
                'record_shift': 'Night Shift',
                'year_week': '202417',
                'work_area': 'Dust Mitigation Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'chen',
                'kaddum_sign': 'chen',
                'kaddum_sign_date': date(2024, 5, 3),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 3),
                'created_date':datetime(2024,5,3,18,20,30),
                'last_modification_date': datetime(2024,5,3,18,20,30),
                'is_draft': True,
                'total_hours_employee':0,
                'total_hours_employee_local': 0,
                'total_hours_employee_indigenous': 0,
                'total_amount_employee': 0,
                'total_hours_equipment': 0,
                'total_amount_equipment': 0,      
            },
            {
                'day_tracking_id': 'DS00005',
                'cost_tracking_id': None,
                'project_no': projects['2439'],
                'record_date': date(2024, 5, 3),
                'record_shift': 'Day Shift',
                'year_week': '202417',  
                'work_area': 'CDU Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'Kabi',
                'kaddum_sign': 'Kabi',
                'kaddum_sign_date': date(2024, 5, 3),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 3),
                'created_date':datetime(2024,5,3,10,20,30),
                'last_modification_date': datetime(2024,5,3,10,20,30),
                'is_draft': False,
                'total_hours_employee':0,
                'total_hours_employee_local': 0,
                'total_hours_employee_indigenous': 0,
                'total_amount_employee': 0,
                'total_hours_equipment': 0,
                'total_amount_equipment': 0,                   
            },
            {
                'day_tracking_id': 'DS00006',
                'cost_tracking_id': None,
                'project_no': projects['2439'],
                'record_date': date(2024, 5, 3),
                'record_shift': 'Night Shift',
                'year_week': '202417',
                'work_area': 'CDU Pit 3',
                'client_representative': 'Jsysen Roach',
                'weather': 'hot and humid',
                'comments': 'no',
                'kaddum_name': 'chen',
                'kaddum_sign': 'chen',
                'kaddum_sign_date': date(2024, 5, 3),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 5, 3),
                'created_date':datetime(2024,5,3,18,20,30),
                'last_modification_date': datetime(2024,5,3,18,20,30),
                'is_draft': False,
                'total_hours_employee':0,
                'total_hours_employee_local': 0,
                'total_hours_employee_indigenous': 0,
                'total_amount_employee': 0,
                'total_hours_equipment': 0,
                'total_amount_equipment': 0,                   
            },
        ]

        for record_data in records:
            DayTracking.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded DayTracking data!'))
