# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from dashboard.models import DayTracking
from datetime import date

class Command(BaseCommand):
    help = 'Seeds the database with DayTracking data'

    def handle(self, *args, **options):
        self.stdout.write('Seeding DayTracking data...')

        records = [
            {
                'day_tracking_no': 'DT0001',
                'project': '2439',
                'record_date': date(2024, 2, 5),
                'record_day': 'Dayshift',
                'shift': 'Dust Mitigation Pit 3',
                'work_area': 'Jsysen Roach',
                'client_representative': 'hot and humid',
                'weather': 'no',
                'employee': 'K0001',
                'role': 'Supervisor',
                'hour_rate': 5,
                'start_time': '6:00',
                'end_time': '18:00',
                'total_hours': '12:00',
                'work_description': 'Amex + LP service',
                'comments': 'no',
                'kaddum_name': 'K0001',
                'kaddum_sign': 'K0001',
                'kaddum_sign_date': date(2024, 2, 5),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 2, 5),
                'submitted_date': date(2024, 2, 5),
                'file_status_code': 'FS01',
            },
            {
                'day_tracking_no': 'DT0002',
                'project': '2439',
                'record_date': date(2024, 2, 5),
                'record_day': 'NightShift',
                'shift': 'Dust Mitigation Pit 3',
                'work_area': 'Jsysen Roach',
                'client_representative': 'hot and humid',
                'weather': 'no',
                'employee': 'K0004',
                'role': 'Supervisor',
                'hour_rate': 5,
                'start_time': '6:00',
                'end_time': '18:00',
                'total_hours': '12:00',
                'work_description': 'Amex + LP service',
                'comments': 'no',
                'kaddum_name': 'K0002',
                'kaddum_sign': 'K0002',
                'kaddum_sign_date': date(2024, 2, 5),
                'client_name': 'Jsysen Roach',
                'client_sign': 'Jsysen Roach',
                'client_sign_date': date(2024, 2, 5),
                'submitted_date': date(2024, 2, 5),
                'file_status_code': 'FS02',
            },
            {
            'day_tracking_no': 'DT0003',
            'project': '2439',
            'record_date': date(2024, 2, 5),
            'record_day': 'Dayshift',
            'shift': 'Dust Mitigation Pit 3',
            'work_area': 'Jsysen Roach',
            'client_representative': 'hot and humid',
            'weather': 'no',
            'employee': 'K0002',
            'role': 'Deck hand',
            'hour_rate': 5,
            'start_time': '6:00',
            'end_time': '18:00',
            'total_hours': '12:00',
            'work_description': 'Line Walking + lp service',
            'comments': 'no',
            'kaddum_name': 'K0002',
            'kaddum_sign': 'K0002',
            'kaddum_sign_date': date(2024, 2, 5),
            'client_name': 'Jsysen Roach',
            'client_sign': 'Jsysen Roach',
            'client_sign_date': date(2024, 2, 5),
            'submitted_date': date(2024, 2, 5),
            'file_status_code': 'FS02',
        },
        {
            'day_tracking_no': 'DT0004',
            'project': '2439',
            'record_date': date(2024, 2, 5),
            'record_day': 'NightShift',
            'shift': 'Dust Mitigation Pit 3',
            'work_area': 'Jsysen Roach',
            'client_representative': 'hot and humid',
            'weather': 'no',
            'employee': 'K0005',
            'role': 'Deck hand',
            'hour_rate': 5,
            'start_time': '6:00',
            'end_time': '18:00',
            'total_hours': '12:00',
            'work_description': 'Line Walking + lp service',
            'comments': 'no',
            'kaddum_name': 'K0002',
            'kaddum_sign': 'K0002',
            'kaddum_sign_date': date(2024, 2, 5),
            'client_name': 'Jsysen Roach',
            'client_sign': 'Jsysen Roach',
            'client_sign_date': date(2024, 2, 5),
            'submitted_date': date(2024, 2, 5),
            'file_status_code': 'FS02',
        },
        ]

        for record_data in records:
            DayTracking.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded DayTracking data!'))
