# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from users.models import UserAccount
from datetime import date
from dashboard.models_resource_cost import ResourceCost
class Command(BaseCommand):
    help = 'Seeds the database with UserAccount'

    def handle(self, *args, **options):
        resource_costs = ResourceCost.objects.all()

        # Create a dictionary mapping resource_id to ResourceCost instance
        resource_cost_map = {resource.resource_id: resource for resource in resource_costs}

        self.stdout.write('Seeding UserAccount data...')

        records = [
            {
                'username': 'KD0001',
                'first_name': 'Clinton',
                'last_name': 'Rasmussen',
                'full_name': 'Clinton Rasmussen',
                'email':None,
                'is_indigenous': False,
                'is_local': True,
                'position_id': resource_cost_map[1],
                'roles': 'super admin',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
            },
            {
                'username': 'KD0002',
                'first_name': 'Melissa',
                'last_name': 'Pettersson',
                'full_name': 'Melissa Pettersson',
                'email':None,
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[1],
                'roles': 'super admin',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
            },
            {
                'username': 'KD0003',
                'first_name': 'Joseph',
                'last_name': 'Jeffries',
                'full_name': 'Joseph Jeffries',
                'email':None,
                'is_indigenous': True,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0004',
                'first_name': 'Rik',
                'last_name': 'Erkelens',
                'full_name': 'Rik Erkelens',
                'email':None,
                'is_indigenous': False,
                'is_local': False,
                'position_id': resource_cost_map[2],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0005',
                'first_name': 'David',
                'last_name': 'Cook',
                'full_name': 'David Cook',
                'email':None,
                'is_indigenous': False,
                'is_local': True,
                'position_id': resource_cost_map[2],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0006',
                'first_name': 'Dave',
                'last_name': 'Bulte',
                'full_name': 'Dave Bulte',
                'email':None,
                'is_indigenous': False,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0007',
                'first_name': 'Andrew',
                'last_name': 'Clark',
                'full_name': 'Andrew Clark',
                'email':None,
                'is_indigenous': True,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0008',
                'first_name': 'Katie',
                'last_name': 'Kiwikiwi',
                'full_name': 'Katie Kiwikiwi',
                'email':None,
                'is_indigenous': True,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0009',
                'first_name': 'Justin',
                'last_name': 'hooker',
                'full_name': 'Justin hooker',
                'email':None,
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[2],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0010',
                'first_name': 'Mark',
                'last_name': 'Reidys',
                'full_name': 'Mark Reidys',
                'email':None,
                'is_indigenous': False,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0011',
                'first_name': 'Tippene',
                'last_name': 'Shepherd',
                'full_name': 'Tippene Shepherd',
                'email':None,
                'is_indigenous': True,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0012',
                'first_name': 'Tyhren',
                'last_name': 'Baker',
                'full_name': 'Tyhren Baker',
                'email':None,
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0013',
                'first_name': 'Nicole',
                'last_name': 'Bancroft',
                'full_name': 'Nicole Bancroft',
                'email':None,
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[2],
                'roles': 'Supervisor',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
            },
            {
                'username': 'KD0014',
                'first_name': 'Mathias ',
                'last_name': 'Liddy',
                'full_name': 'Mathias  Liddy',
                'email':None,
                'is_indigenous': True,
                'is_local': False,
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0015',
                'first_name': 'Joe',
                'last_name': 'Horvath',
                'full_name': 'Joe Horvath',
                'email':None,
                'is_indigenous': False,
                'is_local': False,
                'position_id': resource_cost_map[3],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0016',
                'first_name': 'Stefan',
                'last_name': 'Anderson',
                'full_name': 'Stefan Anderson',
                'email':None,
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[6],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },
            {
                'username': 'KD0017',
                'first_name': 'Mitchell',
                'last_name': 'Theyers',
                'full_name': 'Mitchell Theyers',
                'email':None,
                'is_indigenous': False,
                'is_local': False,
                'position_id': resource_cost_map[6],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': False,
            },

        ]

        for record_data in records:
            UserAccount.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded UserAccount data!'))
