# kaddumapp/management/commands/seed_day_tracking.py
from django.core.management.base import BaseCommand
from users.models import UserAccount
from datetime import date
from dashboard.models_resource_cost import ResourceCost
class Command(BaseCommand):
    help = 'Seeds the database with UserAccount'

    def handle(self, *args, **options):
        resource_costs = ResourceCost.objects.all()

        # Create a dictionary mapping resource_id to ResourceCost instance
        resource_cost_map = {resource.resource_id: resource for resource in resource_costs}

        self.stdout.write('Seeding UserAccount data...')

        records = [
            {
                'username': 'KD0001',
                'first_name': 'Melissa',
                'last_name': 'Pettersson',
                'full_name': 'Melissa Pettersson',
                'email':'KD0001@gmail.com',
                'is_indigenous': True,
                'is_local': True,
                'position_id': resource_cost_map[1],
                'roles': 'supervisor',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
            },
            {
                'username': 'KD0002',
                'full_name': 'Joseph Jeffries',
                'first_name': 'Joseph',
                'last_name': 'Jeffries',
                'email':'KD0002@gmail.com',
                'position_id': resource_cost_map[2],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0003',
                'full_name': 'Rik Erkelens',
                'first_name': 'Rik',
                'last_name': 'Erkelens',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[3],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0004',
                'full_name': 'David Cook',
                'first_name': 'David',
                'last_name': 'Cook',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[5],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0005',
                'full_name': 'Dave Bulte',
                'first_name': 'Dave',
                'last_name': 'Bulte',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[4],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0006',
                'full_name': 'Andrew Clark',
                'first_name': 'Andrew',
                'last_name': 'Clark',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[6],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0007',
                'full_name': 'Katie Kiwikiwi',
                'first_name': 'Katie',
                'last_name': 'Kiwikiwi',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[7],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': False,
            },
            {
                'username': 'KD0008',
                'full_name': 'Justin hooker',
                'first_name': 'Justin',
                'last_name': 'hooker',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[8] ,
                'roles': 'employee',  # You haven't provided a role for this user, please update accordingly
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0009',
                'full_name': 'Clinton Rasmussen',
                'first_name': 'Clinton',
                'last_name': 'Rasmussen',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[9],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': True,
            },
            {
                'username': 'KD0010',
                'full_name': 'Mark Reidys',
                'first_name': 'Mark',
                'last_name': 'Reidys',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[1],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0011',
                'full_name': 'Tippene Shepherd',
                'first_name': 'Tippene',
                'last_name': 'Shepherd',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[2],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': False,
            },
            {
                'username': 'KD0012',
                'full_name': 'Greg McKinnon',
                'first_name': 'Greg',
                'last_name': 'McKinnon',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[3],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0013',
                'full_name': 'Nicole Bancroft',
                'first_name': 'Nicole',
                'last_name': 'Bancroft',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[4],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0014',
                'full_name': 'Jason Mousley',
                'first_name': 'Jason',
                'last_name': 'Mousley',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[9],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0015',
                'full_name': 'Joe Horvath',
                'first_name': 'Joe',
                'last_name': 'Horvath',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[10],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0016',
                'full_name': 'Stefan Anderson',
                'first_name': 'Stefan',
                'last_name': 'Anderson',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[13],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0017',
                'full_name': 'John Smith',
                'first_name': 'John',
                'last_name': 'Smith',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[14],
                'roles': 'employee',
                'is_active': True,
                'is_staff': True,
                'is_superuser': True,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0018',
                'full_name': 'Alice Johnson',
                'first_name': 'Alice',
                'last_name': 'Johnson',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[15],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0019',
                'full_name': 'Emily Brown',
                'first_name': 'Emily',
                'last_name': 'Brown',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[16],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': True,
            },
            {
                'username': 'KD0020',
                'full_name': 'Michael Wilson',
                'first_name': 'Michael',
                'last_name': 'Wilson',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[17],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0021',
                'full_name': 'Emma Lee',
                'first_name': 'Emma',
                'last_name': 'Lee',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[18],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': False,
            },
            {
                'username': 'KD0022',
                'full_name': 'Sophia Williams',
                'first_name': 'Sophia',
                'last_name': 'Williams',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[12],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
            {
                'username': 'KD0023',
                'full_name': 'Matthew Thompson',
                'first_name': 'Matthew',
                'last_name': 'Thompson',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[1],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': True,
                'is_local': False,
            },
            {
                'username': 'KD0024',
                'full_name': 'Olivia Davis',
                'first_name': 'Olivia',
                'last_name': 'Davis',
                'email':'KD0001@gmail.com',
                'position_id': resource_cost_map[1],
                'roles': 'employee',
                'is_active': True,
                'is_staff': False,
                'is_superuser': False,
                'is_indigenous': False,
                'is_local': False,
            },
        ]

        for record_data in records:
            UserAccount.objects.create(**record_data)

        self.stdout.write(self.style.SUCCESS('Successfully seeded UserAccount data!'))
