# Generated by Django 5.0.4 on 2024-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DairyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField()),
                ('record_shift', models.CharField(max_length=10)),
                ('activity_discussion', models.TextField(blank=True, null=True)),
                ('safety_issue_discussion', models.TextField(blank=True, null=True)),
                ('instruction_from_client', models.TextField(blank=True, null=True)),
                ('visitor_on_site', models.TextField(blank=True, null=True)),
                ('daily_progress_description', models.TextField(blank=True, null=True)),
                ('record_comment', models.TextField(blank=True, null=True)),
                ('handover_note', models.TextField(blank=True, null=True)),
                ('record_created_date', models.DateField(auto_now_add=True)),
                ('record_submitted_date', models.DateField(auto_now=True, null=True)),
                ('mobilised', models.IntegerField(blank=True, null=True)),
                ('non_manual', models.IntegerField(blank=True, null=True)),
                ('manual', models.IntegerField(blank=True, null=True)),
                ('subcontractor', models.IntegerField(blank=True, null=True)),
                ('environmental_incidents', models.IntegerField(blank=True, null=True)),
                ('near_misses', models.IntegerField(blank=True, null=True)),
                ('first_aid', models.IntegerField(blank=True, null=True)),
                ('medically_treated_injury', models.IntegerField(blank=True, null=True)),
                ('loss_time_injury', models.IntegerField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
    ]
