# Generated by Django 5.0.4 on 2024-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairyrecord',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='environmental_incidents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='first_aid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='loss_time_injury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='manual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='medically_treated_injury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='mobilised',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='near_misses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='non_manual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='subcontractor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dairyrecord',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
